In [3]:
import numpy as np

# numpy.array와 python.array 차이

np.array = [10, 20] + [20 + 30] -> [30, 50]
python.array = [10, 20] + [20 + 30] -> [10, 20, 20, 30]

np.array = [10, 20] + 5 -> [15, 25]
python.array = [10, 20] * 2 -> [10, 20, 10, 20]

위와 같이 np는 행렬 연산 같이 작동하는 부분이 많음

# numpy 차원 표기

![numpy axis](img/numpy_axis.png)

축(axis) 0부터 시작하며, 
1차원 array [1, 2, 3] axis0 = 3
2차원 array [[1, 2, 3], [1, 2, 3]] axis0 = 2, axis1 = 3

이렇게 정의할 수 있음



# numpy 배열 대표 속성값

### shape
배열의 각 축의 크기 ( axis 0, axis 1 ... 순으로 shape(3, 5) )

### ndim
축의 개수 ( Dimension )

### dtype
각 요소의 타입 ( int64, float32 )

### itemsize
각 요소의 타입의 bytes ( int면 4 이런식으로)

### size

전체 요소의 개수 ( shape(3, 5) 짜리면 15 size가 나옴)

In [4]:
a = np.arange(15).reshape(3, 5)

# a
print(a)

# shape
print(a.shape)

# dtype
print(a.dtype)

# itemsize
print(a.itemsize)

# size
print(a.size)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
int64
8
15


# array 생성

행렬 초기값을 만든다던지, 모델이 정상 동작하는지 알고 싶어서 더미 데이터 만든다던지에 활용되는 것 같음음

### zeros

np.zeros(shape) -> 0으로 구성된 N차원 배열 생성

### ones

np.ones(shape) -> 1로 구성된 N차원 배열 생성

### empty

np.empty(shape) -> 초기화 되지 않은 N차원 배열 생성

In [8]:
# zeros
print(np.zeros((3, 4)))

# ones
print(np.ones((2, 3, 4), dtype=np.int64))

# empty
print(np.empty((3, 4, 5, 6)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[[[8.19210357e-312 8.19200668e-312 2.37151510e-322 1.75920618e-312
    6.95206566e-310 0.00000000e+000]
   [0.00000000e+000 0.00000000e+000 6.95206566e-310 0.00000000e+000
    0.00000000e+000 2.50738315e-320]
   [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
    0.00000000e+000 1.34279247e-231]
   [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
    0.00000000e+000 0.00000000e+000]
   [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
    0.00000000e+000 0.00000000e+000]]

  [[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
    0.00000000e+000 0.00000000e+000]
   [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
    0.00000000e+000 0.00000000e+000]
   [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
    0.00000000e+000 0.00000000e+000]
   [0.00000000e+000 0.00000000e+000 

# np.arange, np.linspace

### np.arange

N 만큼 차이 나는 숫자 생성

np.arange(start=0, stop, step=1)

[start, stop) 임

### np.linspace

N 등분한 숫자 생성

np.linspace(start, stop, num)
처음 값과 끝 값 포함, 몇 개로 만들지 매개변수로 줌
num이 개수 파라미터

In [ ]:
# arange
print(np.arange(10))

print(np.arange(10, 30, 5))

# linspace
print(np.linspace(0, 99, 100)) # 0부터 99까지 100 등분

[0 1 2 3 4 5 6 7 8 9]
[10 15 20 25]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]


In [11]:
# arange 특징
# [start, stop) 이기 때문에
# 가독성을 챙기려고 1+0.25 표현을 사용하기도 한다고함

print(np.arange(0, 1+0.25, 0.25))

[0.   0.25 0.5  0.75 1.  ]


In [12]:
# linspace 특징
# 위 arange에서 구현했던걸 linspace에서 구현을 하면 아래와 같다

print(np.linspace(0, 1, 5)) # 0부터 1까지 5등분 한 것임

[0.   0.25 0.5  0.75 1.  ]


# numpy 기본 연산

### 수치 연산은 기본적으로 element wise 연산
차원을 기준으로 행렬 내에서 같은 위치에 있는 원소끼리 연산을 하는 방식
(행렬 덧샘, 스칼라 곱 같은 느낌)

주의점 : 서로의 차원은 같아야함

### 여러가지 곱셈
'*' : 각각의 원소끼리 곱 ( Elementwise product, Hadamard product )
'@' : 행렬 곱셈 ( Matrix product )

In [15]:
# element wise

a = np.array([10, 20, 30])
b = np.arange(3)

print(a)
print(b)

[10 20 30]
[0 1 2]


In [16]:
# -
print(a - b)

# ^2
print(b**2)

# 스칼라 곱
print(10 * a)

# bool 계산
print(a < 30)

[10 19 28]
[0 1 4]
[100 200 300]
[ True  True False]


In [18]:
# 행렬 곱

A = np.array([
    [1, 1],
    [0, 1]
])
B = np.array([
    [2, 0],
    [3, 4]
])

# 행렬 곱

print(A @ B)

[[5 4]
 [3 4]]


# numpy 집계 함수

### sum

모든 요소의 합

### min

모든 요소 중 최소값

### max

모든 요소 중 최대값

### argmax

모든 요소 중 최대값의 인덱스

### argmin

모든 요소 중 최소값의 인덱스

### cumsum

모든 요소의 누적합

# 집계 함수 axis 값을 매개변수로 입력했을 때

축을 기준으로 연산이 가능하다


0 1 2 3
4 5 6 7
8 9 10 11

있을 때, axis0 이면 [12, 15, 18, 21] 가 나옴

axis1 이면 [6, 22, 38]

# boolean 인덱싱

boolean 타입의 ndarray로 인덱싱 할 수 있음

In [19]:
a = np.arange(12).reshape(3, 4)

b = a > 4 # boolean type array

print(a[b]) # 인덱싱

a[b] = 0
print(a) # true 인 애들만 내가 넣은 값이 0으로 변경됨

[ 5  6  7  8  9 10 11]
[[0 1 2 3]
 [4 0 0 0]
 [0 0 0 0]]


# shape 변경

### ravel

1차원으로 변경

### reshape

shape 넣어준대로 변경

### T

transpose 변환

In [20]:
# reShape
a = np.arange(12).reshape(3, 4)
print(a)

# ravel
print(a.ravel())
# ravel 과 동일
print(a.reshape(-1))

# T
print(a.T)
print(a.T.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(4, 3)


# 데이터 합치기

### vstack

axis 0을 기준으로 쌓음 ( 열 기준으로 )

### hstack

axis 1을 기준으로 쌓음 ( 행 기준으로 )


![vstack, hstack](img/vstack_hstack.png)

# 데이터 쪼개기

### hsplit

N을 넣어서 N등분 시키거나

리스트를 넣어서 axis 1(행)을 기준 인덱스로 분할


![hspilt](img/hspilt.png)

In [21]:
a = np.arange(12).reshape(2, 6)

# hsplit

print(np.hsplit(a, 3))

# 인덱스를 범위 형태로 넣어 줄 수도 있음

print(np.hsplit(a, (3, 4)))

[array([[0, 1],
       [6, 7]]), array([[2, 3],
       [8, 9]]), array([[ 4,  5],
       [10, 11]])]
[array([[0, 1, 2],
       [6, 7, 8]]), array([[3],
       [9]]), array([[ 4,  5],
       [10, 11]])]
